/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yusuke' at '16/11/15 20:34' with Gradle 2.9
 *
 * @author yusuke, @date 16/11/15 20:34
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
